/*
 * This header is generated by classdump-dyld 0.1
 * on Wednesday, September 20, 2017 at 9:22:17 PM Eastern European Summer Time
 * Operating System: Version 11.0 (Build 15A372)
 * Image Source: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
 * classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
 */



@interface _LSQueryResult : NSObject <NSSecureCoding, NSCopying>
+(bool)supportsSecureCoding;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)_init;
//-(id)copyWithZone:(NSZoneRef)arg1 ;
@end

